var dataLayer=dataLayer||[],gtm_products=gtm_products||[];
(function(c,m,w){dataLayer=c.dataLayer;gtm_products=c.gtm_products;var R=c.location.hostname,C=c.location.pathname,H=c.location.hash,A=!1,B=null,S=c.documentLanguage||"tr";m.location.href.indexOf("gadebug");var F=function(){var a={Category:"event_name",Action:"event_action",Label:"event_label",cat1:"kategori_1",cat2:"kategori_2",cat3:"kategori_3",cat4:"kategori_4",cat5:"kategori_5",getPurchase:"CD_GeT",pageType:"CD_PageType",loc1:"CD_Yer1",loc2:"CD_Yer2",loc3:"CD_Yer3",loc4:"CD_Yer4",loc5:"CD_Yer5",
cat6:"CD_Kategori6","motor-hacmi":"CD_MotorHacmi",km:"CD_Km",ULS:"CD_UserLoginState",yakit:"CD_Yakit",vites:"CD_Vites",yil:"CD_ModelYil",kimden:"CD_Kimden","kullanim-tipi":"CD_KullanimTipi",model:"CD_Model","ilan-no":"CD_ilanNo","site-icerisinde":"CD_SiteIcerisinde","bina-yasi":"CD_BinaYasi","kasa-tipi":"CD_KasaTipi",takas:"CD_Takas",ilan_fiyat:"CD_IlanFiyat",classifiedattributeproductcondition:"CD_IlanStatus",HasarSorguHak:"CD_hasarSorguHak",HasarSorguPaket:"CD_HasarSorguPaket","oda-sayisi":"CD_OdaSayisi",
"bulundugu-kat":"CD_Bulundugu_Kat","m-net":"CD_metre_kare","goruntulu-arama-ile-gezilebilir":"CD_goruntulu_arama","motor-gucu":"cd_motorGucu",is_param_guvendeli:"cd_paramGuvende"},b={"oto360/hizmetler/arac-degerleme/basarili-degerleme":"Ara\u00e7 De\u011ferleme - Success","alisveris/ilan-ver":"Al\u0131\u015fveri\u015f Bilgilendirmeler - Landing Page","oto360/hizmetler/hasar-sorgulama/basarili":"Hasar Sorgulama - Success","oto360/hizmetler/arac-detay-sorgulama/basarili":"Hasar Sorgulama - Success",
"emlak360/hizmetler/gayrimenkul-ekspertiz/basarili":"Gayrimenkul Ekspertiz - Success","ilan-verme/tesekkur/bireysel":"\u00d6deme Ekran\u0131 - Success","ilan-verme/tesekkur/kurumsal":"\u00d6deme Ekran\u0131 - Success","sepetDetayi/bireysel/ilan/ikinci-el":"Param G\u00fcvende \u00dcr\u00fcn","adresSecimi/bireysel/ilan/ikinci-el":"Param G\u00fcvende Adres","odeme/bireysel/ilan/ikinci-el":"Param G\u00fcvende \u00d6deme","param-guvende/odeme-basarili":"Param G\u00fcvende Success","param-guvende/kayitli-kredi-karti-odeme-basarili":"Param G\u00fcvende Success",
"oto360/hizmetler/arac-degerleme":"Ara\u00e7 De\u011ferleme Hizmet Sayfalar\u0131","oto360/hizmetler/kredi-teklifleri":"Oto Kredi Teklifleri Hizmet Sayfalar\u0131","emlak360/hizmetler/kredi-teklifleri":"Emlak Kredi Teklifleri Hizmet Sayfalar\u0131","emlak360/hizmetler/gayrimenkul-ekspertiz":"Gayrimenkul Ekspertiz Hizmet Sayfalar\u0131","hizmetler/kredi-teklifleri/step4-auto":"Oto Kredi Teklifleri - Success","hizmetler/kredi-teklifleri/step4-mortgage":"Emlak Kredi Teklifleri - Success","hizmetler/kredi-teklifleri/step4-personal":"\u0130htiya\u00e7 Kredi Teklifleri - Success",
otobid:"Otobid LP","oto360/hizmetler/bakim_onarim":"Oto360 Hizmetler Servis Sayfas\u0131"};return{invoke:function(a){var b=a.event;"virtualPageView"==b?(a=a.pageView,this.callSetUserProperty(),this.callScreenViewLogEvent(a,null)):"gaEvent"==b&&this.callLogEvent(a.Category)},callLogEvent:function(a){var b=this.transformParams();this.logEvent(a,Object.fromEntries(b))},callScreenViewLogEvent:function(a,d){for(var c in b)if(b.hasOwnProperty(c)&&a.includes(c)){a=this.transformParams();a.set("firebase_screen",
b[c]);if(null!=d)for(var l in d)d.hasOwnProperty(l)&&a.set("extra_param_"+l,d[l]);this.logEvent("screen_view",Object.fromEntries(a));break}},callSetUserProperty:function(){for(var a in dataLayer)if(dataLayer.hasOwnProperty(a)){var b=dataLayer[a],c;for(c in b)b.hasOwnProperty(c)&&("shuid"===c?(this.setUserProperty("user_id",b[c]),this.setUserProperty("CD_UserID",b[c])):"ab-guvenli-e-ticaret-uye-ol"===c?this.setUserProperty("guvenli_e_tic_uye_ol",b[c]):"user-age"===c?this.setUserProperty("user_age",
b[c]):"user-age-bin"===c?this.setUserProperty("user-age-bin",b[c]):"MDR"===c?this.setUserProperty("CD_SignupDate",b[c]):"user segment"===c&&this.setUserProperty("CD_UserSegment",b[c]))}this.setUserProperty("user_segment",r("userType"));this.setUserProperty("last_visit",r("lastVisit"));this.setUserProperty("gender_js",r("gender"))},transformParams:function(){var b=new Map,d;for(d in dataLayer)if(dataLayer.hasOwnProperty(d)){var f=dataLayer[d],l;for(l in f)f.hasOwnProperty(l)&&a[l]!==w&&b.set(a[l],
f[l])}var g=new URLSearchParams(c.location.search);d={get:function(a){return g.get(a)}};null!=d.widget_type&&b.set("widget_type",d.widget_type);null!=d.widget_source&&b.set("widget_source",d.widget_source);c.location.referrer!=w&&(d=c.location.referrer,d=d.substring(0,100),b.set("CD_PageReferrer",n(d)));c.location.pathname!=w&&(d=c.location.pathname,d=d.substring(0,100),b.set("CD_Page",n(d)));d=r("lastVisit");null!=d&&b.set("CD_LastVisit",d);c.location.href!=w&&b.set("url",c.location.href);return b},
logEvent:function(a,b){a&&(c.AnalyticsWebInterface?c.AnalyticsWebInterface.logEvent(a,JSON.stringify(b)):c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers.firebase&&c.webkit.messageHandlers.firebase.postMessage({command:"logEvent",name:a,parameters:b}))},setUserProperty:function(a,b){a&&b&&(c.AnalyticsWebInterface?c.AnalyticsWebInterface.setUserProperty(a,b):c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers.firebase&&c.webkit.messageHandlers.firebase.postMessage({command:"setUserProperty",
name:a,value:b}))}}}(),n=function(a,b){var e={"\u00e7\u00c7":"c","\u011f\u011e":"g","\u015f\u015e":"s","\u00fc\u00dc":"u","\u0131\u0130":"i","\u00f6\u00d6":"o"};a=a.toString();for(var c in e)a=a.replace(new RegExp("["+c+"]","g"),e[c]);!0!==b&&(a=a.replace(/[^_-a-zA-Z0-9\s]+/ig,""));return a.replace(/\s/gi,"-").replace(/[-]+/gi,"-").toLowerCase()},g=function(a,b){dataLayer.push(a);b&&(dataLayer.initialized=!0);-1<c.navigator.userAgent.indexOf("EmbeddedBrowser")&&(c.AnalyticsWebInterface||c.webkit&&
c.webkit.messageHandlers&&c.webkit.messageHandlers.firebase)&&F.invoke(a)},G=function(){H=c.location.hash;C=c.location.pathname;var a="/haritada-emlak-arama/ localhost banaozel.sahibinden.com /odeme-yap /emlak360/emlak-endeksi /hizmetler /kategori -hizmetleri /anasayfa-vitrin-ozet / /servisler /banaozel-ozet /kategoriler /emlak360 /oto360".split(" "),b=!1,e;for(e in a){var d=a[e];if(-1<R.indexOf(d)||-1<C.indexOf(d)||-1<H.indexOf(d)){b=!0;break}}return b},h=function(a){if(!0===A&&!1===G())return!1;
var b={event:"virtualPageView"};a&&a.charAt&&(a=("/"===a.charAt(0)?"":"/")+a,b.pageView=a);g(b);A=!0},I=function(a,b){if(!0===A&&!1===G())return!1;a&&a.charAt&&(a=("/"==a.charAt(0)?"":"/")+a,b.pageView=a);g(b);A=!0},x=function(a,b,e,c,f){null==c&&(c=0);g({Category:a,Action:b,Label:f?e:n(e),Value:c,event:"gaEvent"})},p=function(a,b,e){var c={};c[b]=e;g(c);J("gaCustomVarSetted",{index:a,name:b,value:e})},J=function(a,b){var e;m.createEvent?(e=m.createEvent("HTMLEvents"),e.initEvent("shbdn-"+a,!0,!0)):
(e=m.createEventObject(),e.eventType="shbdn-"+a);e.__eventData=b;m.createEvent?m.dispatchEvent(e):m.fireEvent("on"+e.eventType,e)},v,k=function(a){return"/"+a.join("/")+"/"},K=function(a,b){if(a){"undefined"!==typeof a.isStore&&b.push(a.isStore?"kurumsal":"bireysel");"undefined"!==typeof a.isGet&&b.push(a.isGet?"get":"ilan");if("undefined"!==typeof a.categories&&null!=a.categories&&0<a.categories.length)for(b.push("kat"),v=0,length=a.categories.length;v<length;v++)b.push(n(a.categories[v]));"undefined"!==
typeof a.isUsed&&null!==a.isUsed&&"null"!==a.isUsed&&b.push(a.isUsed?"ikinci-el":"sifir");if("undefined"!==typeof a.locations&&null!=a.locations&&0<a.locations.length)for(b.push("yer"),v=0,length=a.locations.length;v<length;v++)b.push(n(a.locations[v]))}},T=function(a,b){var e=Date.now,d=c.requestAnimationFrame,f=e(),l,g=function(){e()-f<b||(f+=b,a());l||d(g)};d(g);return{clear:function(){l=1}}},D={homepage:function(a){a.hasOwnProperty("viewName")&&a.viewName&&h(a.viewName)},login:function(a){a.hasOwnProperty("viewName")&&
a.viewName&&h(a.viewName)},classified:function(a){var b=[],e=a.classified;b.push(e.isGet?"get":"ilan");b.push(e.isActive?"aktif":"pasif");b.push(e.isStore?"kurumsal":"bireysel");"undefined"!==typeof e.isUsed&&null!==e.isUsed&&"null"!==e.isUsed&&b.push(e.isUsed?"ikinci-el":"sifir");b.push("kat");a=0;for(length=e.categories.length;a<length;a++)b.push(n(e.categories[a]));b.push("yer");a=0;for(length=e.locations.length;a<length;a++)b.push(n(e.locations[a]));b=k(b);h(b)},postad:function(a){var b=[],e=
a.view;a=a.classified;b.push("ilan-verme");b.push({addclassified1:"kategori",addclassified2:"detay",classified:"onizleme",doping:"doping",addclassified5:"tesekkur"}[e]);K(a,b);b=k(b);a.isSucceed&&g(a.succeedData);h(b)},search:function(a){var b=[],e,c=a.categories,f=a.locations;b.push("arama");a.hasOwnProperty("viewName")&&a.viewName&&"search"!==a.viewName&&b.push(a.viewName);if("undefined"!==typeof a.searchResult&&null!==a.searchResult&&"null"!==a.searchResult){if(null!==a.searchResult.isGet&&"null"!==
a.searchResult.isGet){var g=C.startsWith("/marka/")||C.startsWith("/brand/");b.push(a.searchResult.isGet?g?"param-guvendeli":"get":"ilan")}null!==a.searchResult.isUsed&&"null"!==a.searchResult.isUsed&&b.push(a.searchResult.isUsed?"ikinci-el":"sifir")}if(0<c.length)for(e in b.push("kat"),c)b.push(n(c[e]));if(0<f.length)for(e in b.push("yer"),f)b.push(n(f[e]));b=k(b);a.query&&(b+="?q\x3d"+a.query);h(b)},s360MyGarage:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);
a=k(b);h(a)}},mapSearch:function(){},category:function(a){var b=[],e;a=a.categories;b.push("kategori");for(e in a)b.push(n(a[e]));b=k(b);h(b)},store:function(a){var b=[],e,c=a.storeSubdomain.categories;b.push("magaza");b.push({2:"emlak",1:"vasita",3:"alisveris",5:"is-makinesi",4:"hayvanlar-alemi",7:"hepsi-bir",9:"yedek-parca"}[a.storeSubdomain.packetId]);if(0<c.length)for(e in b.push("kat"),c)b.push(n(c[e]));b=k(b);a.storeSubdomain.query&&(b+="?q\x3d"+a.storeSubdomain.query);h(b)},storeFacelift:function(){var a=
c.location.href,b="AllClassifieds",e=a.replace(/^[^:]+:\/\/[^/]+/,"").replace(/#.*/,"");0===a.length||-1>=a.indexOf("sahibinden.com")?b="Other":1>=e.length?b="Homepage":-1<e.indexOf("/hakkimizda")?b="AboutUs":-1<e.indexOf("/ekibimiz")&&(b="TeamTab");h("/ofisim/emlak/magaza-sayfasi/"+{Homepage:"anasayfa",AllClassifieds:"tum-ilanlarimiz",TeamTab:"ekibimiz",AboutUs:"hakkimizda"}[b])},payment:function(a){if(a.hasOwnProperty("classified")){var b=[];b.push(a.viewName);K(a.classified,b);a=k(b)}else a="/"+
a.viewName;h(a)},register:function(a){var b={"/kayit/":"/uye-ol/","/eposta-kayit/":"/son-1-adim/"};a=a.view;var c,d;for(d in b)if(-1<d.indexOf(a)){c=b[d];break}else c=a;h(c)},yepyLandingPage:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);b=k(b);I(b,{event:"virtualPageView",CD_ABTest:"0"})}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=0,c=a.trackEvent.length;b<c;b++)x(a.trackEvent[b].category,a.trackEvent[b].action,a.trackEvent[b].label,null,!0)},yepySimpleLandingPage:function(a){if(a.hasOwnProperty("viewName")&&
a.viewName){var b=[];b.push(a.viewName);b=k(b);I(b,{event:"virtualPageView",CD_ABTest:"1"})}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=0,c=a.trackEvent.length;b<c;b++)x(a.trackEvent[b].category,a.trackEvent[b].action,a.trackEvent[b].label,null,!0)},yepySearch:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);b.push("arama");b.push("kat");b.push("ikinci-el-ve-sifir-alisveris");b.push("cep-telefonu");b=k(b);h(b)}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=
0,c=a.trackEvent.length;b<c;b++)x(a.trackEvent[b].category,a.trackEvent[b].action,a.trackEvent[b].label,null,!0)},yepyDetail:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);b.push("ilan");b.push("aktif");b.push("bireysel");b.push("kat");b.push("ikinci-el-ve-sifir-alisveris");b.push("cep-telefonu");b=k(b);h(b)}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=0,c=a.trackEvent.length;b<c;b++)x(a.trackEvent[b].category,a.trackEvent[b].action,a.trackEvent[b].label,
null,!0)},gamer:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push("kategori");b.push("ikinci-el-ve-sifir-alisveris");b.push(a.viewName);a=k(b);h(a)}},lenovo:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);a=k(b);h(a)}},custom:function(a){if(a.hasOwnProperty("viewName")&&a.viewName){var b=[];b.push(a.viewName);b=k(b);h(b)}if(a.hasOwnProperty("trackEvent")&&a.trackEvent)for(var b=0,c=a.trackEvent.length;b<c;b++)x(a.trackEvent[b].category,a.trackEvent[b].action,
a.trackEvent[b].label,null,!0)},error:function(a){a=k(410==a.errorCode||500==a.errorCode?["hata-sayfasi-"+a.errorCode]:["hata-sayfasi"]);h(a)}},r=function(a){a=m.cookie.match(new RegExp("(; )?"+a+"\x3d([^;]*);?"));return null!==a&&2<a.length?a[2]:null},q=function(a,b,c){c||(c=new Date,c.setMonth(c.getMonth()+12));m.cookie=a+"\x3d"+b+";expires\x3d"+c+";domain\x3d.sahibinden.com;"},t=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?\x26]"+a+"\x3d([^\x26#]*)")).exec(location.search);
return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},L=function(){var a=c.pageTrackData,b;if(a&&a.hasOwnProperty("userSegment"))g({"user segment":a.userSegment});else if(b=r("userType"))b=b.replace("_yapi","_ismakineleri"),g({"user segment":b});if(a===w)h();else{b=a.route;g({l:S});g({dc:a.dc||""});a.homepageDesign&&g({homepage_design:a.homepageDesign});a.successfulPaymentWithSavedCC&&g({Category:"Funnel",Action:"kayitliOdeme",Label:"tebrikler",Value:0,event:"gaEvent"});if(a.hasOwnProperty("transactionObject")&&
a.transactionObject){if(a.transactionObject.hasOwnProperty("transactionProducts")&&a.transactionObject.transactionProducts&&0<a.transactionObject.transactionProducts.length){var e=0,d=a.transactionObject.transactionProducts,f=d.length;for(e;e<f;e++)gtm_products.push(d[e])}a.transactionObject.transactionProducts=gtm_products;g(a.transactionObject);a.transactionUserItem&&(g({Category:"Transaction",Action:"Loyalty",Label:"Recurrence",Value:a.transactionUserItem.recurrence,event:"gaEvent"}),g({Category:"Transaction",
Action:"Loyalty",Label:"Delay",Value:a.transactionUserItem.delay,event:"gaEvent"}))}var f=m.referrer,e=-1<c.navigator.userAgent.indexOf("EmbeddedBrowser"),d=-1<c.navigator.userAgent.indexOf("SahibindenPro"),f=0<f.length&&e?"WebView \x3e WebView":w,l="Unknown OS",k=navigator.userAgent;-1!==k.indexOf("like Mac")?l="iOS":-1!==k.indexOf("Android")?l="Android":-1!==k.indexOf("Mac")?l="Macintosh":-1!==k.indexOf("Win")?l="Windows":-1!==k.indexOf("Linux")&&(l="Linux");g({os:l,pixelDensity:c.devicePixelRatio||
0,webView:e,SahibindenPro:d},!0);f&&g({Category:f,Action:a.view,Label:a.viewName,Value:0,event:"gaEvent"});if(b in D)D[b](a);else G()||h();c.invokeAdjustTrackEventForWebview&&("oto360/hizmetler/hasar-sorgulama/basarili"==a.viewName?c.invokeAdjustTrackEventForWebview("jsqdpr"):"oto360/hizmetler/arac-degerleme/basarili-degerleme"==a.viewName?c.invokeAdjustTrackEventForWebview("w493l6"):"odeme-basari"==a.view&&c.invokeAdjustTrackEventForWebview("9ys3ow"))}},M=function(a){if(a){var b=new AdjustConfig("t3skhc6kqha8",
AdjustConfig.EnvironmentProduction);b.setLogLevel(AdjustConfig.LogLevelInfo);b.setOpenDeferredDeeplink(!0);b.setAttributionCallback(function(a){});b.setEventSuccessCallback(function(a){});b.setEventFailureCallback(function(a){});b.setSessionSuccessCallback(function(a){});b.setSessionFailureCallback(function(a){});b.setDeferredDeeplinkCallback(function(a){});if("ios"===a)Adjust.appDidLaunch(b);else if("android"===a)Adjust.onCreate(b)}},y=function(a){if(c.WebViewJavascriptBridge)return a(WebViewJavascriptBridge);
if(c.WVJBCallbacks)return c.WVJBCallbacks.push(a);c.WVJBCallbacks=[a];var b=m.createElement("iframe");b.style.display="none";b.src="https://__bridge_loaded__";m.documentElement.appendChild(b);setTimeout(function(){m.documentElement.removeChild(b)},0)},N=function(){var a=navigator.userAgentData&&navigator.userAgentData.platform||navigator.userAgent,b=/(iPhone|iPod|iPad).*AppleWebKit(?!.*Safari)/i.test(a),a=/wv/i.test(a);return b?"ios":a?"android":""},O=function(){var a=N();return"undefined"!==typeof Adjust&&
("ios"===a||"android"===a)};try{var E=N();"ios"===E?y(function(a){M(E)}):"android"===E&&c.addEventListener("load",function(){M(E)})}catch(a){}y="Yepyeni-std";(new RegExp(/nwsh=fct/)).test(m.cookie)&&(y="Yepyeni-fct");p(1,"Arama Menusu",y,2);p(1,"ilan detay","yeni",2);var z=r("MS1"),u=r("MS2"),P=r("MDR"),y="shuid dopingPurchase dopingTotal dopingFrequency lastDopingPurchase lastVisit getPurchase getTotal getFrequency lastGetPurchase".split(" ");if(z)null!==u&&p(1,"MS2",u,2);else{var z=t("gclid"),Q=
t("utm_source");if(z)z="adwords";else if(Q){if(z=Q,null===u&&(u=t("utm_campaign")))q("MS2",u),p(1,"MS2",u,2)}else z=m.referrer;q("MS1",z)}null!==P&&p(1,"MDR",P,2);if(Object.prototype.hasOwnProperty.call(c,"pageTrackData")){pageTrackData.hasOwnProperty("view")&&pageTrackData.view&&p(1,"pageType",pageTrackData.view,2);if(pageTrackData.hasOwnProperty("customVars")&&pageTrackData.customVars)for(q=0;q<pageTrackData.customVars.length;q++)t=pageTrackData.customVars[q],p(1,n(t.name),t.value?t.value:"",2);
pageTrackData.hasOwnProperty("gaParisClassified")&&pageTrackData.gaParisClassified&&g(pageTrackData.gaParisClassified)}q=null===r("shuid")?0:1;p(1,"ULS",q,2);for(q=0;q<y.length;q++)t=y[q],u=r(t),null!==u&&p(1,t,u,2);(function(){var a=parseInt(r("vid"),10)/10;p(1,"bestmatch-alisveris",0<a&&2>a?"a-2":"b-98",2);p(1,"ab-alisveris_sifir_ikinciel",0<a&&50>a?"a-50":"b-50",2)})();(function(a,b,c,d,f){a[d]=a[d]||[];a[d].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});a=b.getElementsByTagName(c)[0];
c=b.createElement(c);d="dataLayer"!=d?"\x26l\x3d"+d:"";c.setAttributeNode(b.createAttribute("data-ot-ignore"));c.setAttribute("class","optanon-category-C0001");c.async=!0;c.src="//www.googletagmanager.com/gtm.js?id\x3d"+f+d;a.parentNode.insertBefore(c,a)})(c,m,"script","dataLayer","GTM-58T6ZP");(function(a){var b=T(function(){"complete"===m.readyState&&(a(),b.clear())},1)})(L);c.gaTrackData=g;c.gaTrackPageview=h;c.gaReinitializeAndTrackPageview=function(){A=!1;L()};c.gaTrackEvent=x;c.gaTrackEventWithCallback=
function(a,b,c,d,f,g){x(a,b,c,d,g);B=function(){f&&f()};setTimeout(B,500)};c.gaHitCallback=function(){B&&(B(),B=null)};c.gaSetCustomVar=p;c.gaAddItem=function(a,b,c,d,f,g){gtm_products.push({sku:b,name:c,category:d,price:f,quantity:g})};c.gaAddTrans=function(a,b,c,d,f){g({transactionId:a,transactionTotal:c,transactionShipping:f,transactionTax:d,transactionProducts:gtm_products,event:"transaction"})};c.gaTrackTrans=function(){h("_trackTrans")};c.slugify=n;c.gaTrackPostad=D.postad;c.gaTrackPayment=
D.payment;c.gaTrackCustomEvent=function(a,b,c,d,f){f=f?f:0;g({Category:b,Action:c,Label:n(d),Value:f,event:a})};c.gaTriggerEvent=J;c.gaOnEvent=function(a,b){m.addEventListener("shbdn-"+a,function(a){a.__eventData||(a.__eventData={});b.call(this,a.__eventData)})};c.hasDataLayerLanguage=function(){return 0!==dataLayer.filter(function(a){return a.l}).length};c.invokeAdjustTrackEventForWebview=function(a){O()&&(a=new AdjustEvent(a),Adjust.trackEvent(a))};c.setRevenueAndSendAdjustTrackEventForWebview=
function(a,b,c,d){O()&&(a=new AdjustEvent(a),a.setRevenue(b,c),a.addPartnerParameter("categoryToken",d),Adjust.trackEvent(a))};c.gaSetCustomVarWithEvent=function(a,b,c){var d={};d.event=a;d[b]=c;g(d)};c.addEventListener("message",function(a){-1<c.navigator.userAgent.indexOf("EmbeddedBrowser")&&(c.AnalyticsWebInterface||c.webkit&&c.webkit.messageHandlers&&c.webkit.messageHandlers.firebase)&&a.origin===F.koalayDomain&&null!=a.data&&"postMessageForGTM"==a.data.key&&"virtualPageViewKrediTeklifleri"==
a.data.event&&a.data.pageView!==w&&a.data.pageView.includes("step4")&&F.callScreenViewLogEvent(a.data.pageView,a.data)})})(window,document);